---
kind: Service
apiVersion: v1
metadata:
  name: my-spring-app-service 
spec:
  selector:
    app: my-spring-app
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      angularPort: 30002
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-spring-app-deployment 
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: my-spring-app-container 
          image: springdockersample
          ports:
            - containerPort: 8080